### ISSUE TITLE
"https://flashinfer.ai/whl/cu121/torch2.3/ " there is no files.

### ISSUE THREAD

**Issue by JuiceLemonLemon** [microsoft/sarathi-serve#11]
Hello,

I found there is no files in below link.
pip install -e . --extra-index-url https://flashinfer.ai/whl/cu121/torch2.3/

**Comment by AgrawalAmey** [comment]
@JuiceLemonLemon not sure if i follow. Please add error logs and more details about your environment

**Comment by JuiceLemonLemon** [comment]
Thank you very much for your reply, I have found the flashinfer file.
