### ISSUE TITLE
Didn't find the trace files

### ISSUE THREAD

**Issue by zhypku** [microsoft/sarathi-serve#14]
Hi there,

I didn't find the trace files in the repo, e.g., "./data/processed_traces/sharegpt_8k_filtered_stats_llama2_tokenizer.csv" and "./data/processed_traces/arxiv_summarization_filtered_stats_llama2_tokenizer.csv".

Could you please provide the trace files, or at least a huggingface link or something, so that we could download them? That would be helpful for reproducing the results.

Thanks!

**Comment by AgrawalAmey** [comment]
Hi @zhypku , we are trying to understand to figure out the release requirements for these trace files

**Comment by AgrawalAmey** [comment]
@zhypku you can find the traces here: https://github.com/project-metron/metron/tree/main/data/processed_traces
