### ISSUE TITLE
Output of prefill phase

### ISSUE THREAD

**Issue by azamikram** [microsoft/sarathi-serve#22]
Hello,

Thanks for the great project.

I was looking around the code and I noticed that the [`base_sequence_manager`](https://github.com/microsoft/sarathi-serve/blob/main/sarathi/core/sequence_manager/base_sequence_manager.py#L99C1-L101C19) does not utilize the output from the sampler during the prefill stage. It only appends new tokens during the decode phase. Below is the relevant code snippet:

```python
if not seq.prompt_processing_finished:
  seq.update_prompt_tokens_processed(prompt_chunk_len)
  return

seq.append_token_id(sample.output_token)
self._on_append_token(seq)
```

Could you explain the rationale behind not using the output from the prefill stage?

Thank you!

**Comment by AgrawalAmey** [comment]
Hi @azamikram, thanks for bringing this to attention. Fixed this in #23.
