### ISSUE TITLE
Peak memory profiling

### ISSUE THREAD

**Issue by Mrxiangli** [microsoft/sarathi-serve#29]
Hi,

I have a question regarding the `profile_num_available_blocks` function in the `model_runner.py` file. This function calculates the peak memory needed for the model to serve sequences of maximum length at maximum batch size. However, you divide `max_num_batched_tokens` by the batch size. The `max_num_batched_tokens` value comes from `get_max_num_batched_tokens` and in the `VllmSchedulerConfig` class it is set to `max_model_len` unless being specified. Here are the relevant code snippets:

`model_runner.py`
```python
seq_len = max_num_batched_tokens // max_num_seqs + (
    seq_id < max_num_batched_tokens % max_num_seqs
)
```
`config.py`
```python
@dataclass
class VllmSchedulerConfig(BaseSchedulerConfig):

    max_batched_tokens: Optional[int] = None

    def get_max_num_batched_tokens(self, max_model_len: int):
        if self.max_batched_tokens:
            return min(self.max_batched_tokens, max_model_len)
        return max_model_len
```

I'm curious why you calculated the sequence length this way. For example, if we set `max_model_len` to 4096 and the batch size to 16, each sequence will have a length of 256, resulting in a total of 4096 tokens being processed by the model, rather than 4096 * 16 tokens. This can cause the peak memory usage during the profiling phase to differ (specifically the activation memory will be less) from the actual memory usage when processing the sequences with max length. This could lead to a runtime error if the GPU utilization is configured to 100%.

Can you please tell us the reason to calculate the peak memory this way?

Thanks!

**Comment by AgrawalAmey** [comment]
Hi @Mrxiangli,

In the vLLM scheduling policy, the number of tokens in the batch never exceeds to max_num_batch_tokens. This parameter defaults to max_model_len. That is, there will never be a batch of size 4k *16. The profiling strategy is a reflection of that.

Also, utilization fraction of 1 doesn't work because there are other nvidia libraries like nccl and cublas that need some additional gpu memory to operate.

**Comment by Mrxiangli** [comment]
Thanks @AgrawalAmey for the quick answer.

Why is `max_num_batch_tokens` set to `max_model_len` for vLLM? Why there cannot be a batch of 16 sequences each with a length of 4095 given the `max_model_len` is set 4096?

I'm assuming `max_model_len` sets the max length of a _single_ sequence rather than the max token a model can process.

**Comment by Mrxiangli** [comment]
Also, `profile_num_available_blocks` function performs a forward pass on the model to calculate the peak memory. That should have already loaded all the required nvidia libraries that the model needs. Why would the system need more memory after the profiling phase?

**Comment by AgrawalAmey** [comment]
The batched tokens parameter can be set to any value. But it defaults to max model length to minimize activation memory usage (increasing availability for KV cache) without sacrificing either throughput or latency.

Yes, we don't necessarily need more memory for other libs after profiling. But the peak memory measured by pytorch is not total gpu memory usage, but rather the memory used by pytorch.
