### ISSUE TITLE
How to determine token budget

### ISSUE THREAD

**Issue by deciding** [microsoft/sarathi-serve#36]
I didn't find a code to determine the token budget as stated in the paper. 

"We leverage Vidur [28], a LLM inference profiler and simulator to determine the token budget that maximizes system capacity under specific deployment scenario"

after determining it, how should I configure it? I suppose it is `sarathi_scheduler_config_chunk_size`

**Comment by AgrawalAmey** [comment]
Hello @deciding, you can find the code for the simulator here: https://github.com/microsoft/vidur/tree/main/vidur
