### ISSUE TITLE
mismatch figures in osdi-sarathi-serve

### ISSUE THREAD

**Issue by Sunt-ing** [microsoft/sarathi-serve#37]
Hi, I find that the figures in the sarathi-serve are mismatched with the paper. For example, Figure 8 in the paper is about llama2-70b and mistral-7b, while in the osdi-sarathi-serve folder it's about falcon180b and the experiment contents also look mismatched. 
Other figures and corresponding scripts also mismatch.

**Comment by Sunt-ing** [comment]
BTW, why the artifact evaluation branch and the main branch have not merged yet?

**Comment by AgrawalAmey** [comment]
Adding @nitinkedia7 for the first bit. I think broadly the paper has undergone several iterations, so there might be some mismatch between the latest paper version and the artifact scripts.

The main branch of this repo is continuously evolving and right now due to limited bandwidth, it is difficult for us to maintain the artifact scripts up to date. Moreover, considering the general utility of this system, I don't think we want to keep the artifact scripts in the main source tree.

**Comment by Sunt-ing** [comment]
Thanks for your detailed and careful answer! I thought this repo was a research prototype. If not, what's its position now?

**Comment by AgrawalAmey** [comment]
@Sunt-ing sorry for the late response. We are making constant performance improvements to the project. Right now it is not a production ready engine, but other projects can use sarathi as a reference for certain performance enhancements. Later on if we find that there is sufficient reason to use this engine in production, we might decide to work on tech debt and make the system more reliable.

**Comment by Sunt-ing** [comment]
Thanks for your reply! Hopefully the mismatch issue can be solved soon.

**Comment by nitinkedia7** [comment]
Hi @Sunt-ing, below is a mapping which will help you in navigating the mismatch between scripts in the `osdi-sarathi-serve` with the final camera-ready version of the paper available at https://arxiv.org/abs/2403.02310 .

| Camera-ready Figure Number | Corresponding folder in `osdi-sarathi-serve` branch | Comments |
| ------------- | ------------- | -------------  |
| Figure 1 | `figure-1` | |
| Figure 3, 4 | `figure-2` | The two experiments show the same data once in throughput terms and once in absolute latency numbers (inverse of throughput) |
| Figure 6 | Not available | You can repurpose `figure-2` script with attention operation no-oped to get this plot. |
| Figure 9 | Not available | Most closely related to the table2 script. |
| Figure 10 and Figure 11 | `figure-5-6` | |
| Figure 12 | `figure-7` | Subset of data from this script is plotted |
| Figure 13 | `figure-8` | |
| Figure 14 | `figure-9` | |
| Table 4 | `table-6` | |
