### ISSUE TITLE
cannot assign GPU

### ISSUE THREAD

**Issue by Sunt-ing** [microsoft/sarathi-serve#42]
Hi team,

I want to limit the available GPUs and tried CUDA_VISIBLE_DEVICES, but it does not work.

Thanks for your help!

**Comment by AgrawalAmey** [comment]
Hi @Sunt-ing, you can pass in the replica resource mapping string explicitly to use specific gpus

**Comment by Sunt-ing** [comment]
Hi Agrawal, thanks for your reply! As existing yaml files do not use replica_resource_mapping, could you please elaborate on how to do that by example? Thanks!

**Comment by Sunt-ing** [comment]
For example, if I want to use only `cuda:2` when testing the `figure-5-6/mistral7b_relaxed.yml`, how shall I modify it? If I want to use `cuda:2,3,5,6` when testing `figure-5-6/llama70b_relaxed.yml`, how shall I modify it? Thanks for your help! @AgrawalAmey

**Comment by AgrawalAmey** [comment]
i see, if you are using cap search scripts, the easiest option might be to start ray cluster manually with fewer gpus

**Comment by Sunt-ing** [comment]
Thanks!
