### ISSUE TITLE
loss file

### ISSUE THREAD

**Issue by jumbo-q** [microsoft/sarathi-serve#44]
FileNotFoundError: [Errno 2] No such file or directory: './data/processed_traces/sharegpt_8k_filtered_stats_llama2_tokenizer.csv'

is this file avaliable

**Comment by kasohrab** [comment]
I don't believe it is, but a similar file for the arxiv dataset can be downloaded from here: https://github.com/microsoft/vidur/tree/main/data/processed_traces. And then you could point to that.

**Comment by kasohrab** [comment]
New ones can also be generated from running the offline script/benchmark runner and then post-processing the benchmark sequence_metrics output.
